
management:
  server:
    port: 9990
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles:
        # 取得するパーセンタイルの設定（この例だと50%ileと99%ile）
        "http.server.requests": 0.5,0.99
        "http.client.requests": 0.5,0.99
  observations:
    http:
      server:
        requests:
          name: "http.server.requests"

server:
  tomcat:
    mbeanregistry:
      # Tomcatのメトリクス収集を有効化
      enabled: true
    threads:
      # 最大スレッド数の設定（デフォルト:200）
      max: 500
