apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  template:
    spec:
      containers:
        - name: nginx-sidecar
          image: nginx:1.14.2
          ports:
            - containerPort: 8080
