grpc:
  port: 6565

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "*"
  server:
    port: 9991
server:
  port: 8081
