grpc:
  port: 6565

management:
  endpoints:
    web:
      # /prometheusでアクセスできるように
      base-path: "/"
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
server:
  port: 9991
