grpc:
  port: 6565

management:
  metrics:
    export:
      prometheus:
        # prometheusエンドポイントを有効化
        enabled: true
  endpoints:
    web:
      # /prometheusでアクセスできるように
      base-path: "/"
      exposure:
        include: "*"
server:
  port: 9991
