spring:
  application:
    name: springboot

management:
  server:
    # （任意）メトリクスを出力するportを変更する
    # ※エンドポイントさえ知っていれば外から叩けてしまうのでアプリケーションのポートと別にするのがオススメ
    port: 9990
  endpoints:
    web:
      exposure:
        # 有効化したいエンドポイントを記載（ここではprometheusを追加）
        include: health, prometheus
      base-path: /

base64:
  resources:
    # echo -n sample | base64
    sample: "base64:c2FtcGxl"
