spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:./h2db/sample"
  sql:
    init:
      mode: ALWAYS

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
logging:
  level:
    root: info
