spring:
  profiles:
    active: production
logging:
  level:
    root: ${LOGGING_LEVEL:WARN}

line-bot:
  channels:
    tdl:
      secret: "Please set value in production yaml."
      token: "Please set value in production yaml."
    ryobot:
      secret: "Please set value in production yaml."
      token: "Please set value in production yaml."
