all:
  children:
    docker:
      hosts:
        localhost:
          ansible_connection: docker
          ansible_host: ansible-test
    localhost:
      hosts:
        localhost:
          ansible_connection: local