spring:
  batch:
    jdbc:
      initialize-schema: always

  datasource:
    url: "jdbc:h2:mem:test"
    username: sa
    password:
    driver-class-name: org.h2.Driver

#logging:
#  level:
#    root: debug