# prometheus.yml
# localhost:9990/actuator/prometheus を読み込む設定

global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /prometheus
    static_configs:
    - targets: ['host.docker.internal:9990']
