# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x05greet\"\x1c\n\x0cGreetRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rGreetResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2>\n\x05Greet\x12\x35\n\x08greeting\x12\x13.greet.GreetRequest\x1a\x14.greet.GreetResponseB!\n\x14rhirabay.grpc.sampleB\x07GreeterP\x01\x62\x06proto3')



_GREETREQUEST = DESCRIPTOR.message_types_by_name['GreetRequest']
_GREETRESPONSE = DESCRIPTOR.message_types_by_name['GreetResponse']
GreetRequest = _reflection.GeneratedProtocolMessageType('GreetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETREQUEST,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetRequest)
  })
_sym_db.RegisterMessage(GreetRequest)

GreetResponse = _reflection.GeneratedProtocolMessageType('GreetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETRESPONSE,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:greet.GreetResponse)
  })
_sym_db.RegisterMessage(GreetResponse)

_GREET = DESCRIPTOR.services_by_name['Greet']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024rhirabay.grpc.sampleB\007GreeterP\001'
  _GREETREQUEST._serialized_start=23
  _GREETREQUEST._serialized_end=51
  _GREETRESPONSE._serialized_start=53
  _GREETRESPONSE._serialized_end=85
  _GREET._serialized_start=87
  _GREET._serialized_end=149
# @@protoc_insertion_point(module_scope)
