version: '3'
services:
  vt-app:
    container_name: vt-app
    build: .
    ports:
      - "8081:8080"
    environment:
      - VIRTUAL_THREAD=true
      - TOMCAT_THREAD=100
  non-vt-app:
    container_name: non-vt-app
    build: .
    ports:
      - "8082:8080"
    environment:
      - VIRTUAL_THREAD=false
      - TOMCAT_THREAD=100
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
