openapi: 3.0.0
info:
  title: ユーザAPI
  description: ユーザに関する操作を集約したAPI
  version: 0.0.1
servers:
  - url: https://api.example.com/v1
    description: 本番サーバ
paths:
  /users:
    post:
      summary: ユーザ登録
      description: ユーザを登録する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: ユーザ名
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                properties:
                  userId:
                    type: string
                    description: 登録ユーザのユーザ識別子