server:
  port: 8081
  tomcat:
    threads:
      max: 1000

spring:
  pulsar:
    client:
      service-url: "pulsar://localhost:6650"
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      enabled: false


