server:
  port: 8081
  tomcat:
    threads:
      max: 500

spring:
  pulsar:
    client:
      service-url: "pulsar://localhost:6650"
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      enabled: false

management:
  server:
    port: 9990
  endpoints:
    web:
      exposure:
        include: health, prometheus
      base-path: /

restclient:
  base-url: "http://localhost:8081"